# This is a basic workflow to help you get started with Actions

name: funny git

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
  issues:
   types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add git comment
        uses: Marta83/funny-git-action@v2.1
        id: FunnyGit
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ SECRETS.GIPHY_TOKEN }}
          comment: 'gif'
